In [1]:
from utils.config import Config
from utils.database import get_mongo_client_debug
from utils.database import create_dataframe_from_cursor

config = Config()

client = get_mongo_client_debug(config)
caipa_db = client.caipa
caipa_collection = caipa_db.registry
caipa_cursor = caipa_collection.find({})
caipa_df = create_dataframe_from_cursor(caipa_cursor)
caipa_df = caipa_df.drop("id", axis=1)
caipa_df = caipa_df.set_index(caipa_df["centro"])
caipa_df = caipa_df.drop("centro", axis=1)
caipa_df

,elabora,fecha,administradores,trabajadores_sociales,sociologos,personal_mantenimiento,psicologos,promotores_deportivos,medicos,tutor_aula,...,comodato,transporte,estacionamiento_personal,estacionamiento_usuarios,plomeria,ventanas,electricidad,climas,mobiliario,elevadores
centro,,,,,,,,,,,,,,,,,,,,,
APODACA,Lic. Raquel Sanmiguel Andrade,2022-09-30 00:00:00,1,1,0,1,3,0,0,0,...,No,Sí,No,No,Sí,Sí,Sí,Sí,Sí,No Aplica
CADEREYTA,Lic. Maximiliano Israel Robledo,2022-09-30 00:00:00,1,1,0,0,4,0,0,0,...,No,No,Sí,Sí,No Aplica,No Aplica,No Aplica,No Aplica,No Aplica,No Aplica
ESCOBEDO,Lic. Jessica Leticia Cárdenas Quezada,2022-09-30 00:00:00,1,1,0,0,2,0,0,0,...,No,Sí,Sí,Sí,Sí,No,Sí,Sí,No,No Aplica
GARCIA,Lic. Itzel Saavedra Córdova,2022-09-30 00:00:00,1,0,0,2,3,0,0,0,...,No,Sí,No,No,Sí,Sí,Sí,Sí,Sí,No Aplica
GUADALUPE,Lic. Erika Martínez Rocha.,2022-09-30 00:00:00,1,1,0,1,3,0,0,0,...,No,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,No Aplica
JUAREZ,Lic. Josué Misael Reyna Torres,2022-09-30 00:00:00,1,1,0,1,4,0,0,0,...,No Aplica,No,No,No,Sí,Sí,Sí,Sí,No,No Aplica
MONTEMORELOS,Lic. Kassandra Fernández Martínez,2022-09-30 00:00:00,1,1,0,0,2,0,0,0,...,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,No Aplica
MONTERREY,Lic. Aideé Carrillo Olvera,2022-09-30 00:00:00,1,2,0,0,4,0,0,0,...,No,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,No Aplica
PESQUERIA,Lic. Janeth Carolina Mancilla Aguillón,2022-09-30 00:00:00,1,5,0,0,5,0,0,0,...,No Aplica,Sí,Sí,Sí,Sí,No Aplica,Sí,Sí,Sí,No Aplica
SANTA CATARINA,Lic. Alberto Ramírez Herrera,2022-09-30 00:00:00,1,1,0,0,4,0,0,0,...,No,Sí,Sí,Sí,Sí,Sí,Sí,Sí,No,No Aplica
SAN NICOLÁS,Lic. María Francisca Rivera Ramírez,2022-09-30 00:00:00,1,1,0,0,2,0,0,0,...,No,Sí,No,No,Sí,Sí,Sí,Sí,Sí,No Aplica
SAN PEDRO,Lic. Martha Karina García Coronado,2022-09-30 00:00:00,1,2,0,0,3,0,0,0,...,No,Sí,Sí,Sí,No,No,Sí,Sí,No,Sí

In [2]:
caipa_df.columns

Index(['elabora', 'fecha', 'administradores', 'trabajadores_sociales',
       'sociologos', 'personal_mantenimiento', 'psicologos',
       'promotores_deportivos', 'medicos', 'tutor_aula', 'vigilancia',
       'manual_org', 'porcentaje_subsidiado', 'porcentaje_capacitado',
       'acciones_plan', 'centro_subsidio', 'valoracion_medica',
       'psicoterapia_individual', 'psicoterapia_grupal',
       'orientacion_familiar', 'talleres_sociales', 'habilidades_parentales',
       'equidad_genero', 'prevencion_adicciones', 'reincorporacion_escolar',
       'orientacion_vocacional', 'asesoria_legal', 'jovenes_graduados',
       'talleres_prevencion', 'cultura_legalidad', 'ubicacion_centro',
       'direccion', 'presupuesto', 'monto_servicios', 'adscripcion', 'agua',
       'gas', 'internet', 'luz', 'telefonos', 'renta', 'comodato',
       'transporte', 'estacionamiento_personal', 'estacionamiento_usuarios',
       'plomeria', 'ventanas', 'electricidad', 'climas', 'mobiliario',
       'elevadores'],
      dtype='object')

In [3]:
from CAIPA.utils.dict_utils import rh_dict

rh_keys = list(rh_dict.keys())

rh_df = caipa_df[rh_keys]
rh_df

,administradores,trabajadores_sociales,personal_mantenimiento,psicologos,promotores_deportivos,medicos,tutor_aula,vigilancia
centro,,,,,,,,
APODACA,1,1,1,3,0,0,0,0
CADEREYTA,1,1,0,4,0,0,0,0
ESCOBEDO,1,1,0,2,0,0,0,0
GARCIA,1,0,2,3,0,0,0,1
GUADALUPE,1,1,1,3,0,0,0,0
JUAREZ,1,1,1,4,0,0,0,9
MONTEMORELOS,1,1,0,2,0,0,0,0
MONTERREY,1,2,0,4,0,0,0,1
PESQUERIA,1,5,0,5,0,0,0,1
SANTA CATARINA,1,1,0,4,0,0,0,2
SAN NICOLÁS,1,1,0,2,0,0,0,0
SAN PEDRO,1,2,0,3,0,0,0,0

In [4]:
from utils.graphs import get_rh_df

rh_df = get_rh_df(caipa_df)
rh_df

       centro                                      rol  cantidad
0     APODACA                          Administradores         1
1     APODACA                    Trabajadaros Sociales         1
2     APODACA  Personal de mantenimiento o intendencia         1
3     APODACA                               Psicólogos         3
4     APODACA                    Promotores deportivos         0
..        ...                                      ...       ...
91  SAN PEDRO                               Psicólogos         3
92  SAN PEDRO                    Promotores deportivos         0
93  SAN PEDRO                                  Médicos         0
94  SAN PEDRO                          Tutores de aula         0
95  SAN PEDRO                   Personal de vigilancia         0

[96 rows x 3 columns]

In [38]:
import pandas as pd

from CAIPA.utils.dict_utils import val_servicios

valoracion_keys = list(val_servicios.keys())

valoracion_keys.remove("jovenes_graduados")

val_servicios_df = caipa_df[valoracion_keys]
val_servicios_df = val_servicios_df.replace("No aplica", 0)

In [39]:
valoracion_categorical_df = pd.DataFrame(columns = ["centro", "servicio", "cantidad"])

columns = list(val_servicios_df.columns)

for row in val_servicios_df.iterrows():
    centro = row[0]
    for col in columns:
        valoracion_categorical_df = valoracion_categorical_df.append(
            {
                "centro" : centro,
                "servicio" : col,
                "cantidad" : int(row[1][col])
            },
            ignore_index=True
        )

In [40]:
valoracion_categorical_df

        centro                 servicio cantidad
0      APODACA        valoracion_medica       50
1      APODACA  psicoterapia_individual     2050
2      APODACA      psicoterapia_grupal        6
3      APODACA     orientacion_familiar        4
4      APODACA        talleres_sociales        4
..         ...                      ...      ...
151  SAN PEDRO  reincorporacion_escolar        5
152  SAN PEDRO   orientacion_vocacional        0
153  SAN PEDRO           asesoria_legal        6
154  SAN PEDRO      talleres_prevencion       20
155  SAN PEDRO        cultura_legalidad        1

[156 rows x 3 columns]

In [41]:
promedio = val_servicios_df.groupby("centro").sum().describe()
promedio

,valoracion_medica,psicoterapia_individual,psicoterapia_grupal,orientacion_familiar,talleres_sociales,habilidades_parentales,equidad_genero,prevencion_adicciones,reincorporacion_escolar,orientacion_vocacional,asesoria_legal,talleres_prevencion,cultura_legalidad
count,12,12,12,12,12,12,12,12,12,12,12,12,12
unique,12,12,8,11,12,10,8,9,9,7,6,10,4
top,50,2050,06,86,04,00,00,05,05,05,00,02,00
freq,1,1,2,2,1,2,5,3,3,3,4,3,7

In [8]:
import plotly.express as px

px.histogram(valoracion_categorical_df, x="centro", y="cantidad", color="servicio")

In [9]:
from CAIPA.utils.dict_utils import servicios_dict

servicios_keys = list(servicios_dict.keys())

servicios_df = caipa_df[servicios_keys]
servicios_df

               agua        gas internet luz  telefonos
centro
APODACA          Sí  No Aplica       Sí  Sí         Sí
CADEREYTA        Sí  No Aplica       Sí  Sí         Sí
ESCOBEDO         Sí         No       Sí  Sí         Sí
GARCIA           Sí  No Aplica       Sí  Sí         Sí
GUADALUPE        Sí  No Aplica       Sí  Sí         Sí
JUAREZ           Sí  No Aplica       Sí  Sí         Sí
MONTEMORELOS     Sí         No       Sí  Sí         Sí
MONTERREY        Sí  No Aplica       Sí  Sí         Sí
PESQUERIA        Sí  No Aplica       Sí  Sí  No Aplica
SANTA CATARINA   Sí  No Aplica       Sí  Sí         Sí
SAN NICOLÁS      Sí  No Aplica       Sí  Sí         Sí
SAN PEDRO        Sí  No Aplica       Sí  Sí         Sí

In [10]:
fig = px.pie(servicios_df, names = servicios_df["agua"].value_counts().index, values = servicios_df["agua"].value_counts())

fig.update_layout(
    {
        "height" : 400,
        "width" : 600,
        "legend_title_text" : "¿El centro cuenta con servicio de agua?"
    }
)

In [11]:
fig = px.pie(servicios_df, names = servicios_df["gas"].value_counts().index, values = servicios_df["gas"].value_counts())

fig.update_layout(
    {
        "height" : 400,
        "width" : 600,
        "legend_title_text" : "¿El centro cuenta con servicio de gas?"
    }
)

In [12]:
fig = px.pie(servicios_df, names = servicios_df["internet"].value_counts().index, values = servicios_df["internet"].value_counts())

fig.update_layout(
    {
        "height" : 400,
        "width" : 600,
        "legend_title_text" : "¿El centro cuenta con servicio de internet?"
    }
)

In [13]:
fig = px.pie(servicios_df, names = servicios_df["luz"].value_counts().index, values = servicios_df["luz"].value_counts())

fig.update_layout(
    {
        "height" : 400,
        "width" : 600,
        "legend_title_text" : "¿El centro cuenta con servicio de luz?"
    }
)

In [14]:
fig = px.pie(servicios_df, names = servicios_df["telefonos"].value_counts().index, values = servicios_df["telefonos"].value_counts())

fig.update_layout(
    {
        "height" : 400,
        "width" : 600,
        "legend_title_text" : "¿El centro cuenta con servicio de telefonos?"
    }
)

In [15]:
from CAIPA.utils.dict_utils import mantenimiento_dict

mantenimiento_keys = list(mantenimiento_dict.keys())

mantenimiento_df = caipa_df[mantenimiento_keys]
mantenimiento_df

,plomeria,ventanas,electricidad,climas,mobiliario,elevadores
centro,,,,,,
APODACA,Sí,Sí,Sí,Sí,Sí,No Aplica
CADEREYTA,No Aplica,No Aplica,No Aplica,No Aplica,No Aplica,No Aplica
ESCOBEDO,Sí,No,Sí,Sí,No,No Aplica
GARCIA,Sí,Sí,Sí,Sí,Sí,No Aplica
GUADALUPE,Sí,Sí,Sí,Sí,Sí,No Aplica
JUAREZ,Sí,Sí,Sí,Sí,No,No Aplica
MONTEMORELOS,Sí,Sí,Sí,Sí,Sí,No Aplica
MONTERREY,Sí,Sí,Sí,Sí,Sí,No Aplica
PESQUERIA,Sí,No Aplica,Sí,Sí,Sí,No Aplica
SANTA CATARINA,Sí,Sí,Sí,Sí,No,No Aplica
SAN NICOLÁS,Sí,Sí,Sí,Sí,Sí,No Aplica
SAN PEDRO,No,No,Sí,Sí,No,Sí

In [17]:
fig = px.pie(mantenimiento_df, names = mantenimiento_df["plomeria"].value_counts().index, values = mantenimiento_df["plomeria"].value_counts())

fig.update_layout(
    {
        "height" : 400,
        "width" : 600,
        "legend_title_text" : "¿El centro cuenta con servicio de mantenimiento a la plomeria?"
    }
)

In [18]:
fig = px.pie(mantenimiento_df, names = mantenimiento_df["ventanas"].value_counts().index, values = mantenimiento_df["ventanas"].value_counts())

fig.update_layout(
    {
        "height" : 400,
        "width" : 600,
        "legend_title_text" : "¿El centro cuenta con servicio de mantenimiento hacia las ventanas?"
    }
)

In [22]:
fig = px.pie(mantenimiento_df, names = mantenimiento_df["electricidad"].value_counts().index, values = mantenimiento_df["electricidad"].value_counts())

fig.update_layout(
    {
        "height" : 400,
        "width" : 800,
        "legend_title_text" : "¿El centro cuenta con servicio de mantenimiento para la electricidad?"
    }
)

In [23]:
fig = px.pie(mantenimiento_df, names = mantenimiento_df["climas"].value_counts().index, values = mantenimiento_df["climas"].value_counts())

fig.update_layout(
    {
        "height" : 400,
        "width" : 800,
        "legend_title_text" : "¿El centro cuenta con servicio de mantenimiento para los climas?"
    }
)

In [26]:
fig = px.pie(mantenimiento_df, names = mantenimiento_df["mobiliario"].value_counts().index, values = mantenimiento_df["mobiliario"].value_counts())

fig.update_layout(
    {
        "height" : 400,
        "width" : 800,
        "legend_title_text" : "¿El centro cuenta con servicio de mantenimiento para el mobiliario?"
    }
)

In [27]:
fig = px.pie(mantenimiento_df, names = mantenimiento_df["elevadores"].value_counts().index, values = mantenimiento_df["elevadores"].value_counts())

fig.update_layout(
    {
        "height" : 400,
        "width" : 800,
        "legend_title_text" : "¿El centro cuenta con servicio de mantenimiento para los elevadores?"
    }
)